# ФІ-12 Завалій Олександр
## Варіант №4
---
$
R = 
\begin{bmatrix}
    0 & 0 & 1 & 1 & 0  \\
    0 & 0 & 1 & 1 & 0  \\
    1 & 1 & 0 & 1 & 1 \\
    1 & 1 & 1 & 0 & 1 \\
    0 & 0 & 1 & 1 & 0
\end{bmatrix}$

In [105]:
import numpy as np

In [106]:
matrix = np.array([
    [0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0],
    [1, 1, 0, 1, 1],
    [1, 1, 1, 0, 1],
    [0, 0, 1, 1, 0]
])

### Бінарні відношення.
Рефлексивність \
(aRa)

In [107]:
np.all(np.diag(matrix) == 1)

False

Антирефлексивність \
$\neg(aRa)$

In [108]:
np.all(np.diag(matrix) == 0)

True

Симетричність \
$aRb\Rightarrow bRa$

In [109]:
np.array_equal(matrix, matrix.T)

True

Антисиметричність \
$aRb\wedge bRa \Rightarrow a=b$

In [110]:
np.all(matrix + matrix.T == 0)

False

Асиметричність \
$aRb \Rightarrow \neg(bRa)$

In [111]:
np.all((matrix & matrix.T) == 0)

False

Транзитивність \
$\forall a,b,c \in X,\: aRb \wedge bRc \Rightarrow aRc$

In [112]:
R_square = np.square(matrix)
print(np.all(R_square <= matrix))

True


Найбільший, найменший , максимальний та мінімальний елементи. \
$R=\begin{bmatrix}
    0 & 0 & 1 & 1 & 0  \\
    0 & 0 & 1 & 1 & 0  \\
    1 & 1 & 0 & 1 & 1 \\
    1 & 1 & 1 & 0 & 1 \\
    0 & 0 & 1 & 1 & 0
\end{bmatrix}$

In [113]:
print('Найбільший|найкращий:', np.where(np.all(matrix == 1, axis=1))[0])
print('Найменший|найгірший:', np.where(np.all(matrix == 1, axis=0))[0])

Найбільший|найкращий: []
Найменший|найгірший: []


In [114]:
print(matrix - matrix.T)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [115]:
max_elem = np.where(np.all(matrix - matrix.T == 0, axis=1))[0]

print('Максимальний:', max_elem)

Максимальний: [0 1 2 3 4]


In [116]:
min_elem = np.where(np.all(matrix - matrix.T == 0, axis=0))[0]

print('Мінімальний:', min_elem)

Мінімальний: [0 1 2 3 4]


Обернене відношення

In [117]:
matrix.T

array([[0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0]])

Додаткове відношення

In [118]:
1 - matrix

array([[1, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1]])