# ФІ-12 Завалій Олександр
## Варіант №4
---
$$
R_1=
\begin{pmatrix}
  1 & 0.3 & 0.4 & 0.5 & 0.1 \\
  0.3 & 1 & 0.7 & 0.3 & 0.7 \\
  0.9 & 0 & 1 & 0.9 & 0.7 \\
  0.3 & 0.5 & 0.6 & 1 & 0.4 \\
  0.2 & 0.5 & 0.7 & 0.9 & 1
\end{pmatrix}
\:\:\:\:\:
R_2=
\begin{pmatrix}
  1 & 0 & 1 & 0 & 0.6 \\
  1 & 1 & 0.9 & 0.4 & 1 \\
  0 & 0.7 & 1 & 0 & 0.7 \\
  0.5 & 0.3 & 0 & 1 & 0.7 \\
  1 & 0.9 & 0.8 & 0.3 & 1
\end{pmatrix}$$
$\lambda_1=0.5,\:\:\lambda_2=0.5$

In [1]:
import numpy as np

In [2]:
R1 = np.array([
    [1, 0.3, 0.4, 0.5, 0.1],
    [0.3, 1, 0.7, 0.3, 0.7],
    [0.9, 0, 1, 0.9, 0.7],
    [0.3, 0.5, 0.6, 1, 0.4],
    [0.2, 0.5, 0.7, 0.9, 1]
])

R2 = np.array([
    [1, 0, 1, 0, 0.6],
    [1, 1, 0.9, 0.4, 1],
    [0, 0.7, 1, 0, 0.7],
    [0.5, 0.3, 0, 1, 0.7],
    [1, 0.9, 0.8, 0.3, 1]
])

In [3]:
Q1 = np.minimum(R1, R2)

nu_Q1_1 = 1 - np.max(np.maximum(Q1 - Q1.T, 0), axis=1)

lambda1 = 0.5
lambda2 = 0.5

Q2 = lambda1 * R1 + lambda2 * R2

nu_Q2_1 = 1 - np.max(np.maximum(Q2 - Q2.T, 0), axis=1)

nu_2 = np.minimum(nu_Q1_1, nu_Q2_1)

max_nu_2 = np.max(nu_2)
rational_choices = np.where(nu_2 == max_nu_2)[0]

print('Fuzzy relation Q1:')
print(Q1)
print('\nA fuzzy subset of non-dominated alternatives (Q1):')
print(nu_Q1_1)
print('\nFuzzy relation Q2:')
print(Q2)
print('\nA fuzzy subset of non-dominated alternatives (Q2):')
print(nu_Q2_1)
print('\nIntersection of sets:')
print(nu_2)
print('\nAlternatives:')
print(rational_choices + 1)

Fuzzy relation Q1:
[[1.  0.  0.4 0.  0.1]
 [0.3 1.  0.7 0.3 0.7]
 [0.  0.  1.  0.  0.7]
 [0.3 0.3 0.  1.  0.4]
 [0.2 0.5 0.7 0.3 1. ]]

A fuzzy subset of non-dominated alternatives (Q1):
[0.6 0.3 1.  0.7 0.9]

Fuzzy relation Q2:
[[1.   0.15 0.7  0.25 0.35]
 [0.65 1.   0.8  0.35 0.85]
 [0.45 0.35 1.   0.45 0.7 ]
 [0.4  0.4  0.3  1.   0.55]
 [0.6  0.7  0.75 0.6  1.  ]]

A fuzzy subset of non-dominated alternatives (Q2):
[0.75 0.5  0.85 0.85 0.75]

Intersection of sets:
[0.6  0.3  0.85 0.7  0.75]

Alternatives:
[3]
