In [38]:
import numpy as np
import matplotlib.pyplot as plt

### Task 1

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

# Відношення R
R = {(2, 2), (2, 3), (2, 4), (3, 2), (3, 3), (3, 4)}

# Множина A
A = {1, 2, 3, 4}

# Побудова матриці відношення R
matrix_R = np.zeros((len(A), len(A)), dtype=int)

for pair in R:
    matrix_R[pair[0]-1][pair[1]-1] = 1

print("Матриця відношення R:")
print(matrix_R)

Матриця відношення R:
[[0 0 0 0]
 [0 1 1 1]
 [0 1 1 1]
 [0 0 0 0]]


### Task 2

In [40]:
# Обчислюємо R^2
R_square = []

for pair1 in R:
    for pair2 in R:
        if pair1[1] == pair2[0]:
            R_square.append((pair1[0], pair2[1]))

# Обчислюємо обернене відношення R
R_inv = [(pair[1], pair[0]) for pair in R]

# Знаходимо перетин R^2 і R_inv
R_intersection = list(set(R_square) & set(R_inv))

# Друк результату
print("Перетин R^2 і R^{-1}:")
print(R_intersection)


Перетин R^2 і R^{-1}:
[(2, 3), (3, 2), (3, 3), (2, 2)]


In [41]:
np.logical_and(np.dot(matrix_R, matrix_R), matrix_R.T)

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False]])